/* SPDX-License-Identifier: AGPL-3.0-only */
/* Copyright (C) 2026 Amine Khemissi */
/**
 * MakhOS - net/ipv4.c
 * IPv4: header validation, routing, ARP gleaning and protocol dispatch.
 * No fragmentation/reassembly: fragments are dropped, we always send DF.
 */

#include <net/net.h>
#include <errno.h>
#include <lib/string.h>

extern int  net_in_netd(void);
extern void arp_update(uint32_t ip, const uint8_t mac[ETH_ALEN]);
extern const uint8_t* eth_rx_src_mac(const uint8_t* ip_payload);

#define IP_DEFAULT_TTL 64
#define IP_FLAG_DF     0x4000
#define ARP_WAIT_MS    1000

static uint16_t ip_id_counter = 1;
static uint8_t ip_tx_buf[ETH_MTU];   /* protected by net_lock */

static int is_local_ip(uint32_t ip) {
    for (int i = 0; i < netdev_count(); i++) {
        netdev_t* d = netdev_get(i);
        if (d->up && d->ip == ip) return 1;
    }
    return 0;
}

/* ---------------------------------------------------------------- routing */

netdev_t* ipv4_route(uint32_t dst, uint32_t* next_hop) {
    netdev_t* lo = netdev_by_name("lo");

    /* Loopback range, or one of our own addresses: deliver locally. */
    if ((dst >> 24) == 127 || is_local_ip(dst)) {
        if (next_hop) *next_hop = dst;
        return lo;
    }

    /* Directly connected subnet. */
    for (int i = 0; i < netdev_count(); i++) {
        netdev_t* d = netdev_get(i);
        if (!d->up || d->is_loopback || d->ip == 0) continue;
        if ((dst & d->netmask) == (d->ip & d->netmask)) {
            if (next_hop) *next_hop = dst;
            return d;
        }
    }

    /* Limited broadcast goes out the default interface. */
    netdev_t* def = netdev_default();
    if (dst == 0xFFFFFFFFu && def) {
        if (next_hop) *next_hop = dst;
        return def;
    }

    /* Everything else via the default gateway. */
    if (def && def->up && def->gateway) {
        if (next_hop) *next_hop = def->gateway;
        return def;
    }
    return NULL;
}

/* Source address we would use to reach dst (needed for TCP/UDP checksums). */
uint32_t ipv4_src_for(uint32_t dst) {
    uint32_t hop;
    netdev_t* d = ipv4_route(dst, &hop);
    if (!d) return 0;
    if (d->is_loopback) return ((dst >> 24) == 127) ? d->ip : dst;
    return d->ip;
}

/* ---------------------------------------------------------------- input */

void ipv4_input(netdev_t* dev, const uint8_t* pkt, size_t len) {
    if (len < sizeof(ipv4_hdr_t)) { net_stats.ip_bad++; return; }
    const ipv4_hdr_t* h = (const ipv4_hdr_t*)pkt;

    if ((h->ver_ihl >> 4) != 4) { net_stats.ip_bad++; return; }
    size_t ihl = (size_t)(h->ver_ihl & 0x0F) * 4;
    if (ihl < sizeof(ipv4_hdr_t) || ihl > len) { net_stats.ip_bad++; return; }

    size_t total = ntohs(h->total_len);
    if (total < ihl || total > len) { net_stats.ip_bad++; return; }

    if (inet_checksum(h, ihl) != 0) { net_stats.ip_bad++; return; }

    /* No reassembly: drop any fragment (MF set or non-zero offset). */
    if (ntohs(h->frag_off) & 0x3FFF) { net_stats.ip_bad++; return; }

    uint32_t src = ntohl(h->src);
    uint32_t dst = ntohl(h->dst);

    /* Accept unicast to us (any local address arrives via lo), broadcast, or
     * subnet broadcast. */
    int for_us = (dst == dev->ip) || dev->is_loopback || dst == 0xFFFFFFFFu ||
                 (dev->netmask && dst == (dev->ip | ~dev->netmask));
    if (!for_us) return;

    net_stats.ip_rx++;

    /* Glean the sender's MAC for on-link peers, so replies generated by netd
     * never have to wait on ARP. */
    if (!dev->is_loopback && dev->netmask && src != 0 &&
        (src & dev->netmask) == (dev->ip & dev->netmask)) {
        arp_update(src, eth_rx_src_mac(pkt));
    }

    const uint8_t* payload = pkt + ihl;
    size_t plen = total - ihl;

    switch (h->proto) {
        case IPPROTO_ICMP: icmp_input(dev, src, dst, payload, plen); break;
        case IPPROTO_UDP:  udp_input(dev, src, dst, payload, plen);  break;
        case IPPROTO_TCP:  tcp_input(dev, src, dst, payload, plen);  break;
        default: break;
    }
}

/* ---------------------------------------------------------------- output */

int ipv4_send(uint32_t dst, uint8_t proto, const void* payload, size_t len) {
    if (len + sizeof(ipv4_hdr_t) > ETH_MTU) return -EMSGSIZE;

    uint32_t next_hop;
    netdev_t* dev = ipv4_route(dst, &next_hop);
    if (!dev) { net_stats.dropped_no_route++; return -ENETUNREACH; }

    /* Resolve the link-layer address FIRST: it is the only step that may drop
     * net_lock (while waiting for an ARP reply). Building into the shared
     * ip_tx_buf afterwards means nothing can clobber it before eth_send. */
    uint8_t mac[ETH_ALEN];
    int rc = arp_resolve(dev, next_hop, mac, net_in_netd() ? 0 : ARP_WAIT_MS);
    if (rc != 0) { dev->tx_dropped++; return rc; }

    ipv4_hdr_t* h = (ipv4_hdr_t*)ip_tx_buf;
    h->ver_ihl = (4 << 4) | 5;
    h->tos = 0;
    h->total_len = htons((uint16_t)(sizeof(ipv4_hdr_t) + len));
    h->id = htons(ip_id_counter++);
    h->frag_off = htons(IP_FLAG_DF);
    h->ttl = IP_DEFAULT_TTL;
    h->proto = proto;
    h->checksum = 0;
    h->src = htonl(ipv4_src_for(dst));
    h->dst = htonl(dst);
    h->checksum = inet_checksum(h, sizeof(ipv4_hdr_t));
    memcpy(ip_tx_buf + sizeof(ipv4_hdr_t), payload, len);

    net_stats.ip_tx++;
    return eth_send(dev, mac, ETHERTYPE_IPV4, ip_tx_buf, sizeof(ipv4_hdr_t) + len);
}
