#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Amine Khemissi
#
# Generate the framebuffer console font (kernel/include/fb_font.h): an 8x16
# antialiased bitmap for printable ASCII (32..126), rendered from a free
# monospace TTF. Each glyph is 8*16 = 128 coverage bytes (0=bg, 255=fg),
# row-major. Run: python3 tools/genfont.py
import sys
from PIL import Image, ImageFont, ImageDraw

CELL_W, CELL_H = 8, 16
FIRST, LAST = 32, 126
FONT = "/mnt/skills/examples/canvas-design/canvas-fonts/IBMPlexMono-Regular.ttf"
OUT = "kernel/include/fb_font.h"

# Pick the largest point size whose glyph advance fits the cell width.
font = None
for size in range(CELL_H, 8, -1):
    f = ImageFont.truetype(FONT, size)
    w = f.getbbox("M")[2]
    if w <= CELL_W:
        font = f
        break
if font is None:
    font = ImageFont.truetype(FONT, 12)

# Vertical placement: use the font metrics so glyphs sit on a common baseline.
asc, desc = font.getmetrics()
baseline = CELL_H - desc - 1
if baseline + desc > CELL_H:
    baseline = CELL_H - 2

glyphs = []
for c in range(FIRST, LAST + 1):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    ch = chr(c)
    bb = font.getbbox(ch)
    gw = bb[2] - bb[0]
    x = (CELL_W - gw) // 2 - bb[0]            # center horizontally
    d.text((x, baseline - asc), ch, fill=255, font=font)
    glyphs.append(list(img.getdata()))

with open(OUT, "w") as o:
    o.write("/* SPDX-License-Identifier: AGPL-3.0-only */\n")
    o.write("/* Copyright (C) 2026 Amine Khemissi */\n")
    o.write("/* Framebuffer console font: 8x16 antialiased glyphs for ASCII "
            "32..126, generated by tools/genfont.py from IBM Plex Mono "
            "(SIL OFL 1.1, a separate work). Do not edit by hand. */\n")
    o.write("#ifndef MAKH_FB_FONT_H\n#define MAKH_FB_FONT_H\n")
    o.write("#define FB_FONT_W %d\n#define FB_FONT_H %d\n" % (CELL_W, CELL_H))
    o.write("#define FB_FONT_FIRST %d\n#define FB_FONT_COUNT %d\n"
            % (FIRST, LAST - FIRST + 1))
    o.write("static const unsigned char fb_font[FB_FONT_COUNT][FB_FONT_W*FB_FONT_H] = {\n")
    for g in glyphs:
        o.write("  {" + ",".join(str(v) for v in g) + "},\n")
    o.write("};\n#endif\n")
print("genfont: wrote %s (size %dpt, baseline %d)" % (OUT, font.size, baseline))
