#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Amine Khemissi
#
# Generate the boot-splash logo (kernel/include/fb_logo.h): a downscaled 8-bit
# alpha coverage mask of the MAKH fennec logo. The source art is light line-work
# on white; on MAKH's dark splash the mask is drawn in cream, so we take the
# "ink" (distance from white, times the source alpha) as coverage and normalise
# it so the faint lines read clearly. The generated header is committed; the
# source PNG lives outside the repo and is passed as an argument.
#
#   python3 tools/genlogo.py <logo.png> [target_width]
import sys
from PIL import Image

SRC = sys.argv[1]
TARGET_W = int(sys.argv[2]) if len(sys.argv) > 2 else 420
OUT = "kernel/include/fb_logo.h"
PREVIEW = sys.argv[3] if len(sys.argv) > 3 else None

im = Image.open(SRC).convert("RGBA")
W, H = im.size
px = im.load()

def ink_at(x, y):
    r, g, b, a = px[x, y]
    lum = (r + g + b) // 3
    return (255 - lum) * a // 255

# Bounding box of visible ink.
THR = 10
minx, miny, maxx, maxy = W, H, 0, 0
for y in range(H):
    for x in range(W):
        if ink_at(x, y) > THR:
            if x < minx: minx = x
            if y < miny: miny = y
            if x > maxx: maxx = x
            if y > maxy: maxy = y
if maxx < minx:
    print("genlogo: no ink found", file=sys.stderr); sys.exit(1)

crop = im.crop((minx, miny, maxx + 1, maxy + 1))
cw, ch = crop.size
tw = TARGET_W
th = max(1, round(ch * tw / cw))
crop = crop.resize((tw, th), Image.LANCZOS)
cpx = crop.load()

# Coverage per pixel, then normalise so the 99.5th percentile maps to 255.
cov = [[0] * tw for _ in range(th)]
vals = []
for y in range(th):
    for x in range(tw):
        r, g, b, a = cpx[x, y]
        lum = (r + g + b) // 3
        v = (255 - lum) * a // 255
        cov[y][x] = v
        vals.append(v)
vals.sort()
hi = vals[int(len(vals) * 0.995)] or 255
gain = 255.0 / hi
for y in range(th):
    for x in range(tw):
        v = int(cov[y][x] * gain)
        cov[y][x] = 255 if v > 255 else v

with open(OUT, "w") as o:
    o.write("/* SPDX-License-Identifier: AGPL-3.0-only */\n")
    o.write("/* Copyright (C) 2026 Amine Khemissi */\n")
    o.write("/* MAKH fennec boot-splash logo: %dx%d 8-bit alpha coverage, "
            "generated by tools/genlogo.py. Do not edit by hand. */\n" % (tw, th))
    o.write("#ifndef MAKH_FB_LOGO_H\n#define MAKH_FB_LOGO_H\n")
    o.write("#define FB_LOGO_W %d\n#define FB_LOGO_H %d\n" % (tw, th))
    o.write("static const unsigned char fb_logo[FB_LOGO_W*FB_LOGO_H] = {\n")
    for y in range(th):
        o.write("".join("%d," % cov[y][x] for x in range(tw)) + "\n")
    o.write("};\n#endif\n")

if PREVIEW:
    prev = Image.new("RGB", (tw, th), (0x1b, 0x18, 0x16))
    pp = prev.load()
    cr, cg, cb = 0xfd, 0xf8, 0xf0
    bg = (0x1b, 0x18, 0x16)
    for y in range(th):
        for x in range(tw):
            a = cov[y][x]
            pp[x, y] = (bg[0] + (cr - bg[0]) * a // 255,
                        bg[1] + (cg - bg[1]) * a // 255,
                        bg[2] + (cb - bg[2]) * a // 255)
    prev.save(PREVIEW)

print("genlogo: wrote %s (%dx%d, gain %.2f)" % (OUT, tw, th, gain))
